# -*- coding: utf-8 -*-
"""Det_Demog_beta.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/raz-mon/Thermo2_Project/blob/main/Deterministic_with_Demography.ipynb
"""

import numpy as np
from scipy.integrate import odeint
import matplotlib.pyplot as plt

# Birth and Death rate
mu = 3.5/40 
# Total population, N.
N = 1000
# Initial number of infected and recovered individuals, I0 and R0.
I0, R0 = 1, 0
# Everyone else, S0, is susceptible to infection initially.
S0 = N - I0 - R0
# Contact rate, beta, and mean recovery rate, gamma, (in 1/days).
beta = 3
gamma = 1./1
# A grid of time points (in days)
t = np.linspace(0, 100, 100)

# The SIR model differential equations.
def deriv(y, t, N, beta, gamma):
    S, I, R = y
    dSdt = -beta * S * I / N + mu*(N-S)
    dIdt = beta * S * I / N - (gamma) * I - mu*I 
    dRdt = gamma * I - mu*R
    return dSdt, dIdt, dRdt

# Initial conditions vector
y0 = S0, I0, R0
# Integrate the SIR equations over the time grid, t.
ret = odeint(deriv, y0, t, args=(N, beta, gamma))
S, I, R = ret.T

fig = plt.figure(facecolor='w')
ax = fig.add_subplot(111, axisbelow=True)
ax.plot(t, S, 'b', alpha=0.5, lw=2, label='Susceptible')
ax.plot(t, I, 'r', alpha=0.5, lw=2, label='Infected')
ax.plot(t, R, 'g', alpha=0.5, lw=2, label='Recovered')
ax.set_xlabel('Time [days]')
ax.set_ylabel('N')
ax.set_ylim([0,N+100])
ax.yaxis.set_tick_params(length=0)
ax.xaxis.set_tick_params(length=0)
ax.set_facecolor('whitesmoke')
plt.title('')     # Detereministic with Demography
ax.grid(b=True, which='major', c='w', lw=3, ls='-')
legend = ax.legend(loc = 'best')
legend.get_frame().set_alpha(0.5)

#plt.savefig("/Users/edenmautner/Desktop/Thermo2i" + str(i))

